-- ============================================================
-- DB_Logistica - PostgreSQL
-- Conversión desde SQL Server
-- Ejecutar este script conectado a la base de datos DB_Logistica
-- ============================================================

CREATE SCHEMA IF NOT EXISTS "l";	

-- ============================================================
-- TABLA: Camion
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Camion" (
    "ID_CA" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Placas" varchar(15) NOT NULL,
    "Modelo" varchar(20),
    "Kilometraje_total" numeric(10,2),
    "Capacidad_tanque" integer,
    "Capacidad_carga" integer NOT NULL,
    CONSTRAINT "PK_Camion" PRIMARY KEY ("ID_CA"),
    CONSTRAINT "UQ_Camion_Placas" UNIQUE ("Placas")
);

-- ============================================================
-- TABLA: Usuario
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Usuario" (
    "ID_Usuario" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Correo" varchar(100) NOT NULL,
    "Password_Hash" varchar(225) NOT NULL,
    "Rol" varchar(20) NOT NULL,
    "preguntarec" varchar(100),
    "resprec" varchar(100),
    CONSTRAINT "PK_Usuario" PRIMARY KEY ("ID_Usuario"),
    CONSTRAINT "UQ_Usuario_Correo" UNIQUE ("Correo")
);

-- ============================================================
-- TABLA: Chofer
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Chofer" (
    "ID_Chof" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ID_Usuario" integer,
    "NSS" varchar(20),
    "Nombre" varchar(100),
    "Licencia" varchar(30),
    "Edad" integer,
    "Sexo" char(1),
    CONSTRAINT "PK_Chofer" PRIMARY KEY ("ID_Chof"),
    CONSTRAINT "FK_Chofer_Usuario" FOREIGN KEY ("ID_Usuario")
        REFERENCES "l"."Usuario" ("ID_Usuario")
);

-- ============================================================
-- TABLA: Cliente
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Cliente" (
    "ID_CLI" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ID_Usuario" integer,
    "Nombre" varchar(100),
    "Telefono" varchar(20),
    "Estado" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Cliente" PRIMARY KEY ("ID_CLI"),
    CONSTRAINT "FK_Cliente_Usuario" FOREIGN KEY ("ID_Usuario")
        REFERENCES "l"."Usuario" ("ID_Usuario")
);

-- ============================================================
-- TABLA: Gastos_Camion
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Gastos_Camion" (
    "ID_GCA" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ID_ca" integer,
    "Fecha_Gasto" date,
    "Tipo_Gasto" varchar(50),
    "Concepto" varchar(100),
    "Monto" numeric(19,4),
    "Kilometraje_Al_Momento" numeric(10,2),
    "Proximo_Aviso" date,
    CONSTRAINT "PK_Gastos_Camion" PRIMARY KEY ("ID_GCA"),
    CONSTRAINT "FK_Gastos_Camion_Camion" FOREIGN KEY ("ID_ca")
        REFERENCES "l"."Camion" ("ID_CA")
);

-- ============================================================
-- TABLA: Viaje
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Viaje" (
    "ID_Viaje" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Folio_ruta" varchar(10),
    "Origen" varchar(100),
    "Destino" varchar(100),
    "Mercancia" varchar(100),
    "Peso_Mercancia" numeric(6,2),
    "Distancia" numeric(6,2),
    "Fecha_partida" date,
    "Fecha_aprox_llegada" date,
    "Fecha_real_llegada" date,
    "Pago_Cliente" numeric(19,4),
    "Estado" varchar(20) DEFAULT 'Presupuesto',
    "ID_cli" integer,
    "ID_ca" integer,
    "ID_cho" integer,
    CONSTRAINT "PK_Viaje" PRIMARY KEY ("ID_Viaje"),
    CONSTRAINT "UQ_Viaje_Folio_ruta" UNIQUE ("Folio_ruta"),
    CONSTRAINT "FK_Viaje_Cliente" FOREIGN KEY ("ID_cli")
        REFERENCES "l"."Cliente" ("ID_CLI"),
    CONSTRAINT "FK_Viaje_Camion" FOREIGN KEY ("ID_ca")
        REFERENCES "l"."Camion" ("ID_CA"),
    CONSTRAINT "FK_Viaje_Chofer" FOREIGN KEY ("ID_cho")
        REFERENCES "l"."Chofer" ("ID_Chof")
);

-- ============================================================
-- TABLA: Gastos_Viaje
-- ============================================================
CREATE TABLE IF NOT EXISTS "l"."Gastos_Viaje" (
    "ID_Gasto_Viaje" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ID_Viaje" integer,
    "Tipo_Gasto" varchar(50),
    "Concepto" varchar(100),
    "Monto_Presupuestado" numeric(19,4) DEFAULT 0,
    "Monto_Comprobado" numeric(19,4) DEFAULT 0,
    "Fecha_Registro" timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Gastos_Viaje" PRIMARY KEY ("ID_Gasto_Viaje"),
    CONSTRAINT "FK_Gastos_Viaje_Viaje" FOREIGN KEY ("ID_Viaje")
        REFERENCES "l"."Viaje" ("ID_Viaje")
);

select * from public."Usuario" 
select * from public."Cliente" 
select * from public."Chofer" 
select * from public."Viaje"

BEGIN;

ALTER TABLE IF EXISTS l."Camion" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Chofer" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Cliente" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Gastos_Camion" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Usuario" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Viaje" SET SCHEMA public;
ALTER TABLE IF EXISTS l."Gastos_Viaje" SET SCHEMA public;

DROP SCHEMA IF EXISTS l;

COMMIT;

CREATE OR REPLACE FUNCTION public.generar_folio_ruta()
RETURNS VARCHAR(10)
LANGUAGE plpgsql
AS $$
DECLARE
    fecha_actual DATE;
    prefijo TEXT;
    siguiente_numero INTEGER;
    folio TEXT;
BEGIN

    fecha_actual := CURRENT_DATE;

    prefijo := 'CLI' || TO_CHAR(fecha_actual, 'DDMM');

    /*
     * Bloquea únicamente las solicitudes que están generando
     * folio para este día.
     *
     * Esto evita que dos solicitudes simultáneas obtengan
     * el mismo consecutivo.
     */
    PERFORM pg_advisory_xact_lock(
        hashtext(prefijo)
    );

    /*
     * Buscar el último consecutivo utilizado hoy.
     */
    SELECT COALESCE(
        MAX(
            CAST(
                RIGHT("Folio_ruta", 3)
                AS INTEGER
            )
        ),
        0
    ) + 1
    INTO siguiente_numero
    FROM public."Viaje"
    WHERE "Folio_ruta" LIKE prefijo || '%';

    IF siguiente_numero > 999 THEN
        RAISE EXCEPTION
            'Se alcanzó el máximo de 999 viajes para el día %',
            fecha_actual;
    END IF;

    folio :=
        prefijo ||
        LPAD(siguiente_numero::TEXT, 3, '0');

    RETURN folio;

END;
$$;

SELECT
    conname,
    conrelid::regclass AS tabla
FROM pg_constraint
WHERE conname = 'UQ_Viaje_Folio_ruta';

ALTER TABLE public."Viaje"
ALTER COLUMN "Folio_ruta"
SET DEFAULT public.generar_folio_ruta();

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;




